### ISSUE TITLE
Please remove or rename the documentation folder

### ISSUE THREAD

**Issue by mudrd8mz** [NMAI-lab/moodle-mod_socialwiki#26]
Hi guys. The folder `socialwiki documentation` is causing us some troubles as it contains the space and it breaks some automated tests here. May I ask you to either remove that folder completely (and have the docs available online only) or rename it to something like `documentation` or even `docs`. Thanks.

**Comment by bencroskery** [comment]
The folder has now been renamed to documentation and slimmed down to only the few most important files.

**Comment by bencroskery** [comment]
The folder has now been renamed to documentation and slimmed down to only the few most important files.

**Comment by mudrd8mz** [comment]
I can still see file / dirs like `socialwiki documentation/` or `documentation/socialwiki documentation.pdf`. I know it is basically a problem on our side as our tools should handle spaces in filenames. Still, having the files there makes it impossible for us to run some automated acceptance tests.
