### ISSUE TITLE
PHP parse error

### ISSUE THREAD

**Issue by mudrd8mz** [NMAI-lab/moodle-mod_socialwiki#28]
While attempting to preview a page, I am getting

    Parse error: syntax error, unexpected '.', expecting ')' in /mod/socialwiki/parser/markups/nwiki.php on line 60

**Comment by bencroskery** [comment]
I haven't been able to replicate this issue, it may have actually been fixed in the past few days or I might have missed the right steps to encounter the error.
Would you be able to explain what was done to get this parse error?

**Comment by bencroskery** [comment]
Actually we have now decided that we are going to drop the creole and nwiki editors and stick to using the atto editor exclusively to simplify things in the code and for the users.
This problem should be gone as it's in the nwiki markup.

**Comment by mudrd8mz** [comment]
>  drop the creole and nwiki editors

Nice, I was tempted to suggest that, too :-)
