### ISSUE TITLE
Invalid class names

### ISSUE THREAD

**Issue by mudrd8mz** [NMAI-lab/moodle-mod_socialwiki#30]
Please see https://docs.moodle.org/dev/Plugin_contribution_checklist#Namespace-collisions

There is classes like `peer` or those in the pagelib.php that violate the expected naming scheme.

Let me suggest to look at the class autoloading support in Moodle (https://docs.moodle.org/dev/Automatic_class_loading) that will help you to avoid issues like this. Additionally, you can use PHP namespaces (not necessary but some developers prefer it).

**Comment by mudrd8mz** [comment]
Similarly, functions like `ouwiki_diff_internal()` may cause collisions in certain situations. It might be better to wrap the OU library into a class (with proper name prefix related to your module) and call them as static methods of that class maybe?

**Comment by bencroskery** [comment]
All classes now have a socialwiki prefix and the ouwiki functions have been renamed with the prefix as well.
