### ISSUE TITLE
Behat features uses invalid @tag

### ISSUE THREAD

**Issue by mudrd8mz** [NMAI-lab/moodle-mod_socialwiki#31]
The tag `@mod_wiki` is not valid in your features files, it should be the component name of your plugin - `@mod_socialwiki`.

**Comment by mudrd8mz** [comment]
In fact, it seems that these files are not valid Behat scenario tests for your plugin at all?!

**Comment by bencroskery** [comment]
We've removed these tests for now as they have come straight from the wiki module this plugin is based off of.
