### ISSUE TITLE
 ERROR: column "teacher" does not exist

### ISSUE THREAD

**Issue by mudrd8mz** [NMAI-lab/moodle-mod_socialwiki#34]
This is thrown on PostgreSQL and seems to be caused by using double quotes in comparisons. Yet another reason why parameter binding via placeholders is recommended.

**Comment by mudrd8mz** [comment]
Debug info: ERROR: column "teacher" does not exist
LINE 4: WHERE contextid=$1 AND (shortname="teacher" OR s...
^
SELECT ra.userid AS id
FROM mdl_role_assignments ra
JOIN mdl_role r ON r.id=ra.roleid
WHERE contextid=$1 AND (shortname="teacher" OR shortname="editingteacher")
[array (
0 => 88,
)]
Error code: dmlreadexception
Stack trace:

    line 443 of /lib/dml/moodle_database.php: dml_read_exception thrown
    line 244 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
    line 764 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
    line 1726 of /mod/socialwiki/locallib.php: call to pgsql_native_moodle_database->get_records_sql()
    line 228 of /mod/socialwiki/locallib.php: call to socialwiki_get_teachers()
    line 71 of /mod/socialwiki/home.php: call to socialwiki_get_first_page()

**Comment by bencroskery** [comment]
This has been fixed now, replacing "teacher" and "editingteacher" with ? and adding them as parameters.
I believe this is the only case where an sql query wasn't using parameter binding via placeholders.
