### ISSUE TITLE
hard-coded role names used instead of capability checks.

### ISSUE THREAD

**Issue by danmarsden** [NMAI-lab/moodle-mod_socialwiki#37]
The correct way to check for user permissions is using capabilities, many organisations use custom roles or rename the existing roles like "teacher", "editingteacher".

You should define some custom capabilities in your activity assigned to the teacher/editingteacher roles by default and check those capabilities within the course instead of looking for the teacher/editingteacher roles which may not exist.

**Comment by bencroskery** [comment]
There were already capabilities defined but they weren't always used.
Assuming I was looking at this correctly, this problem should be fixed now.

**Comment by danmarsden** [comment]
yep - you removed that here:
https://github.com/NMAI-lab/moodle-mod_socialwiki/commit/ba6f732ef8e2b3df1b874e8f3e44002ead859a9a#diff-528c47baf0e31a7dcd6c3042a2182b9cL1562

great!
