### ISSUE TITLE
is PARAM_RAW really needed?

### ISSUE THREAD

**Issue by danmarsden** [NMAI-lab/moodle-mod_socialwiki#39]
https://github.com/jed15/socialwiki/blob/master/edit.php#L45

looks like this is supposed to be some form of array of hashes - maybe optional_param_array() could be used with an appropriate PARAM rather than RAW?

**Comment by bencroskery** [comment]
That's correct, and looking through the code that paramater doesn't need to be there at all, so I've simply removed it from the code entirely now.
