### ISSUE TITLE
Invalid parameters submitted for search.php

### ISSUE THREAD

**Issue by mudrd8mz** [NMAI-lab/moodle-mod_socialwiki#50]
Looking at the Social Wiki Home page, tab Pages. The page title is a link to search.php script and the parameter `cmid` is provided. However, the script expects that parameter be named `id` and throws fatal error `invalidcoursemodule` (line 39).

**Comment by bencroskery** [comment]
I'm suprised I didn't find this during testing but it has been fixed now, the parameters were reorganized earlier and this one was missed when changing the names.
