### ISSUE TITLE
Unable to use the selec drop-down menu

### ISSUE THREAD

**Issue by mudrd8mz** [NMAI-lab/moodle-mod_socialwiki#52]
When looking at the Versions tab and I select the mode "List View", I end up on a page like `versions.php?pageid=7&view=1`. On this page, the HTML element with CSS class `dataTables_filter` has the property `margin-top` set to -2.6em and it effectively covers the area where the drop-down menu selector is. So I can't click it any more. Being abel to reproduce on Chrome and Firefox (both Linux).

**Comment by bencroskery** [comment]
The problem here is that the search box for the table is in front of the dropdown.
I could simply give the dropdown a high z-index to fix the problem but I've decided instead to just remove the margin and leave extra whitespace between elements to avoid any overlap when the window width is small.
