### ISSUE TITLE
Direct access to superglobal $_SESSION

### ISSUE THREAD

**Issue by mudrd8mz** [NMAI-lab/moodle-mod_socialwiki#53]
The file peer.php accesses the superglobal `$_SESSION` variable. This is discouraged in Moodle. The preferred way is to avoid using session at all (there are other mechanisms how to store per-user preferences, and caching should be done via MUC). If the session is needed, it should be accessed via Moodle core's global `$SESSION` object. To avoid conflict, I would suggest to use something like `$SESSION->mod_socialwiki` as a root element for your session storage eventually.

**Comment by bencroskery** [comment]
Has been fixed in 548634435e3e6d29f544cc943cafb2bf9cb2c646.
