### ISSUE TITLE
Views dropdown inaccessible in List View

### ISSUE THREAD

**Issue by esfandia** [NMAI-lab/moodle-mod_socialwiki#54]
To reproduce this bug (this was found on the Demo node using the Agents Wiki) : 
1- go to any entry and click on the "versions" tab
2- from there, select the "list view" from the drop down
3- now that you're in List View, try selecting anything form that same drop down. It won't work, because I imagine that the drop down area overlaps with the selectable columns below, so you end up sorting a column instead.

**Comment by bencroskery** [comment]
Yes, this issue was actually fixed a week ago except I had not merged the changes in yet.
The version on Moodle already has the fixes applied to it.
