### ISSUE TITLE
Search box overlaps with list view table

### ISSUE THREAD

**Issue by esfandia** [NMAI-lab/moodle-mod_socialwiki#57]
I don't know if this is a problem everywhere, but on the demo node, using the Agent Wiki, if you click on a Coalition formation entry and then choose the list view, the table is aligned nicely under the list view drop down, but the search box is covered by some of the titles of each column of the table. It's probably a matter of putting things in divs and tables, but I'm not an expert in these things...

**Comment by bencroskery** [comment]
This seems to be a bug specifically with Firefox, which is why I hadn't noticed it before.
It shouldn't be too hard to find a workaround for this.

**Comment by esfandia** [comment]
I am happy to report that updating to the latest Firefox made the problem go away!

**Comment by bencroskery** [comment]
The issue should now be fixed for older versions of Firefox.
