### ISSUE TITLE
tree view should be centred on top of the tree

### ISSUE THREAD

**Issue by esfandia** [NMAI-lab/moodle-mod_socialwiki#58]
Again, looking at the coalition formation entry on the demo node, but this time using the tree view, initially all you see is a horizontal scrollbar. It's not an issue per se but it can be confusing to the user. One way to make sure there's always something appearing in this view is to center it around the top of the tree, instead of having the scroll bar all the way to the left. Not sure if that's something that can be done though.

**Comment by bencroskery** [comment]
The scrollbar should now be centered on page load for the tree view and you should be able to at least see the very top node in the center of the screen.
