### ISSUE TITLE
round up followers to two digits after the decimal points

### ISSUE THREAD

**Issue by esfandia** [NMAI-lab/moodle-mod_socialwiki#59]
The followers metric is giving too many significant digits after the decimal point (11 or 12 at least!). Rounding it up to two digits after the decimal should be more than enough.

**Comment by bencroskery** [comment]
Would you be able to give me an example of where you see this? I believe I have seen that somewhere as well although I can't seem to replicate it.
I may have also fixed it recently and you noticed this before the server had been updated.

**Comment by esfandia** [comment]
Try the Coalition Formation page on the demo node. Pick any version, then go to the tree view, then back to a list view. You'll see one of the followers value at 4.5555555555556.

**Comment by bencroskery** [comment]
A rounding was missing specifically for this type of table, it should round to 2 decimal places the same as everywhere else now.
