### ISSUE TITLE
Moodle Plugin page

### ISSUE THREAD

**Issue by esfandia** [NMAI-lab/moodle-mod_socialwiki#8]
Let's make sure we're following the Moodle plugin guidelines so that we can make SocialWiki available on their web site.

**Comment by ntartania** [comment]
Plugin contribution checklist is here:
https://docs.moodle.org/dev/Plugin_contribution_checklist

**Comment by ntartania** [comment]
There are two php automated code checkers, one of which integrates with eclipse. They are recommended by moodle coding guidelines page ( see https://docs.moodle.org/dev/Coding_style).

**Comment by ntartania** [comment]
Regarding javascript, the guidelines are here:
https://docs.moodle.org/dev/JavaScript_guidelines
Having everything work without javascript is "no longer a requirement". But the plugin should not be completely unusable without js.

**Comment by esfandia** [comment]
Did you see what they say about CSS styles:

"Make sure to use properly namespaced selectors so that your style 
sheets can be safely concatenated with the ones provided by other 
plugins. Plugin specific CSS selectors are needed to make sure that your 
styling does not accidentally affect other parts of Moodle outside your 
plugin scope. For example, instead of the selector .contentarea it is 
better to use something like .path-mod-mymodule .contentarea as the 
.path-* classes are automatically added by the Moodle core renderers to 
the HTML <body> tag."

Could that be the problem we had with our stylesheet?

ntartania wrote:

**Comment by mudrd8mz** [comment]
Hi, David here from the Moodle Plugins directory approval team. Yeah, the selectors like `.emptycomments` are tricky as they are likely to be applied elsewhere. Note that every page of your plugin has some CSS classes added to the body tag by the Moodle core itself. So you may fix it by using something like `.path-mod-socialwiki .emptycomments` (see core activity modules for reference).

**Comment by bencroskery** [comment]
Instead of using the .path-mod-socialwiki class, the socialwiki area is encompassed by a .socialwiki_wikicontent class. This is used everywhere as it won't modify the entire page, just the plugin main region, leaving the sidebar blocks, header and footer alone.

**Comment by esfandia** [comment]
Can this be closed now?
